name: Continuous Integration

on: [push, pull_request]
# for testing purposes. Will focus on main branch after thia workflow is integrated

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout latest source
        uses: actions/checkout@v2

      - name: Install package dependencies
        run: npm ci

      - name: Build react app (board)
        run: npm run build

      - name: Save build artifacts
        uses: actions/upload-artifact@main
        with:
          name: board artifacts
          path: public/

  lint:
    name: Lint & Format (eslint)
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout latest source
        uses: actions/checkout@v2

      - name: Lint
        run: npm run lint
