name: Continuous Integration

on: [push, pull_request]
# for testing purposes. Will focus on main branch after thia workflow is integrated

jobs:
  install:
    name: Install packages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: npm-${{ hashFiles('package-lock.json') }}
          restore-keys: npm-
      - run: npm install

  build:
    needs: install
    runs-on: ubuntu-latest

    steps:
      - name: Checkout latest source
        uses: actions/checkout@v2

      #- name: Install package dependencies
      #  run: npm ci

      - name: Build react app (board)
        run: npm run build

      - name: Save build artifacts
        uses: actions/upload-artifact@main
        with:
          name: board artifacts
          path: public/
