name: Continuous Integration

on: [push, pull_request]
# for testing purposes. Will focus on main branch after thia workflow is integrated

jobs:

  install:
    name: Install packages
    runs-on: ubuntu-latest
    steps:
      - name: checkout latest source
        uses: actions/checkout@v2

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: npm-${{ hashFiles('package-lock.json') }}
          restore-keys: npm-

      - name: npm ci
        run: npm ci --ignore-scripts

  lint:
    name: Lint & Format (eslint)
    needs: install
    runs-on: ubuntu-latest
    steps:
      - name: Lint
        run: npm run lint
