name: Tests

on:
  push: # Branch pushes only, not tags
    branches:
      - "**"
  workflow_call: # Allow other workflows to call this one

jobs:
  lint:
    name: npm run lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: npm ci
      - run: npm run lint

  check:
    name: npm run check
    needs: [lint]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: npm ci
      - run: npm run check

  unit:
    name: npm run test:unit
    needs: [check]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: npm ci
      - run: npm run test:unit

  build:
    name: npm run build
    needs: [check]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: npm ci
      - run: npm run build
